#+title: multispack = manylinux + Spack

* Introduction

*multispack* uses Spack to build against a "floor" glibc version (2.28) so that the resulting binaries run on most current and future glibc/Linux distributions.  This basic idea is shared by [[https://github.com/pypa/manylinux][manylinux]] which is used to build the general Python ecosystem.

* Additional optional features

- Build in podman containers for hermetic, reproducible builds and to provide a post-EOL build environment.
- Factor large ecosystems into Spack Environment "groups" to keep concretization times reasonable.
- Integrate [[https://github.com/brettviren/spaxi][spaxi]] to export the Spack-built binaries to Conda package channels that can be installed with [[https://pixi.prefix.dev/][pixi]].

* Outline of a multispack build:

1. Pick the "base glibc" version (2.28) and a distro that provides it (Alma 8).
2. Define a minimal "base" container providing both including as host GCC.
3. Perform a one-time "bootstrap ladder" to produce a "builder" container with Spack and Spack-built compilers and no OS-provided compilers.
4. Use "builder" container as a base for all Spack builds.
5. Deploy the binaries in interesting ways.

* Deploying binaries

With glibc 2.28, the binaries work on Debian 12+ Alma 8+ and SLES 15+ (NERSC's
distro) and is expected to support all other and future distros with suitably
newer glibc.

Supported deployments:

- Simply use the resulting podman volumes holding Spack Install area and binary buildcache.
- Export the buildcache to be served over HTTP for external Spack installs.
- Export the Spack Install area to a Conda package channel for use with pixi.
- more t.b.d.

* Multispack caveats 

- Linux + glibc only :: The implementation picks glibc but the pattern may work with others such as [[https://musl.libc.org/][musl]] using [[https://alpinelinux.org/][alpine linux]] to provide the "builder" container.  It may be applicable to Apple and Microsoft operating systems but I have no personal interest in that.
- Relies on glibc contract :: glibc does not remove symbols in new versions that were added in past versions. If that contract breaks, binaries build on glibc 2.28 may not work on subsequent glibc-based distros.  glibc 2.28 was released in 2018 and (on AMD64) supports back to =GLIBC_2.2.5=  which was released in 2002.  Given this long history, even if the contract breaks it likely would "merely" require upgrading the "builder" container and dropping support for what would likely be already obsolete runtime.  (Eg, a hypothetical future could see the need to drop support for Alma 12 in order to support glibc on Alma 22).

* Development

multispack is in a phase of super fast development.  Current drive is to consolidate the proof of principle into a well-integrated Python package (=mspack=).  This will then be the basis for how to extend to support long-horizon life-cycle of software ecosystem version and build management.

